name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0  
  google_fonts: ^4.0.0
  rive: 0.9.1
  sqflite: any
  path: any


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/animations/

flutter_icons:
  ios: true
  image_path: 'assets/icons/icon.png' 
  remove_alpha_ios: true